version: '3'
services:
  nestjs-app:
    build: 
      dockerfile: dockerfile
    ports:
      -3000:3000
    env_file:
      - .env
    depends_on:
      - postgres

postgres:
  image: postgres
  environment:
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_NAME: ${DB_NAME}
  ports:
    - 5432:5432